# -*- coding: utf-8 -*-
"""Basic01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SPv21po0e85Cnb98j1ItUGOtuABxBepY

Create five variables
"""

import math

first_name="Safiyyah"
firstName="Sarah"
FirstName="Sukhyang"
FIRSTNAME="ACE"

print(first_name)
print(firstName)
print(FirstName)
print(FIRSTNAME)

"""Create 10 Last Name Variables

"""

lastname = "Kazim"
last_name = "Mendez"
LastName = "Canalizo"
Last_Name = "Jeong"
LASTNAME = "De La Cruz"
Lastname = "May"
lastName = "Lopez"
last_Name = "Britt"
LAST_NAME = "Kang"
name_last="Chu"

print(lastname)
print(last_name)
print(LastName)
print(Last_Name)
print(LASTNAME)
print(LastName)
print(Lastname)
print(last_name)
print(LAST_NAME)
print(name_last)

num = 10

print(first_name)

first_name=90

print(first_name)

"""Data Types"""

num5 = 12.900900090909090909

num5

math.pi

game=True

type(num5)

type(game)

list=['name', 'time', 'carrots']

list

"""Create 10 list, 10 bool, 10 floats"""

num=1.1
num2=2.2
num3=3.3
num4=4.4
num5=5.5
num6=6.6
num7=7.7
num8=8.8
num9=9.9
num10=10.10

num

num2

list = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
list4 = ["hello","world"]
list5 = ["list", "list2"]
list6 = [23,42,66]
list7 = [78,92,56]
list8 = ['yes', 'no']
list9 = ['yes', 'or', 'yes']

list4

hello=True
goodbye=False
yes=True
no=False

myDict={'key':'value', 'key2':'value2', 'key3':'value3'}

myDict

"""Create:
dict1=10 foods
dict2=10 people names
dict3=5 sport player
"""

dict1={'pizza':'bbq chicken', 'fried chicken':'grilled chicken', 'french fries':'mozzarella sticks', 'cheeseburger':'hamburger','chicken tenders':'chicken nuggets'}

dict1

dict2={'kim namjoon':'kim seokjin', 'min yoongi':'jeong hoseok','park jimin':'kim taehyung','jeon jungkook':"kim jennie",'lalisa manoban':'kim jisoo'}

dict2

dict3={'basketball':'lebron james', 'football':'michael jordan', 'tennis':'serena williams', 'volleyball':'venus williams', 'soccer':'lionel messi'}

dict3

